### ISSUE TITLE
Licenses seem to contradict each other

### ISSUE THREAD

**Issue by wooorm** [hyspell/HySpell_3.0.1#1]
Hi! Thanks for HySpell! I am not Armenian nor do I speak or write Armenian, but it’s wonderful to see how people advance their languages by building quality spell checkers, and this looks great!

One project I work on is [`wooorm/dictionaries`](https://github.com/wooorm/dictionaries), which exposes dictionaries for use mostly in JavaScript, and I was wondering if I could add HySpell as well (specifically, the aff and dic files).

However, there are different licenses used here, so I’m a bit confused (disclaimer: IANAL):

* The readme states that HySpell is open source (or is only the Microsoft Office Add-in tool open source?)
* `LICENSE.md` includes something very close to [MIT](https://opensource.org/licenses/MIT), but I believe `along with author's memo` makes it so that it isn’t open source anymore
* Is it correct that the .aff and .dic file are *not* open source? The license files inside [the installers](https://github.com/hyspell/HySpell_3.0.1#links-to-hyspell-spellchecker-installers) state they are not

**Comment by nikita-moor** [comment]
I am the maintainer of the [hunspell-hy](https://aur.archlinux.org/packages/hunspell-hy-reformed/) package in Arch Linux. Currently, it is stated the license of the dictionaries is MIT, and I do not think adding a "memo" invalidates the license. Anyway, commentary of the author would be appreciated.

**Comment by hyspell** [comment]
Hi wooorm, Yes all material in this git-hub site is open source, and can be used at LGPL or MIT license state. So, you can use it for any purpose, as long as authors credits/notes are intact.
Note that morphological descriptive fields (e.g. verb,adverb, etc.) are missing in the current version.
I have also extended Nodehun, please check my fork at Nodehun.
Thanks for you comments.
Regards
Haro
